services:
  backend:
    build: ./fastapi-service
    platform: linux/amd64
    image: rb-ocr-backend:latest
    container_name: rb-ocr-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./runs:/app/runs
    environment:
      - TZ=Asia/Almaty
      - DB_HOST=10.0.94.227
      - DB_PORT=5432
      - DB_NAME=rbocrdb
      - DB_USER=rbocruser
      - DB_PASSWORD=rbocruserDEV
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 10s
      retries: 3