services:
  backend:
    build: ./fastapi-service
    platform: linux/amd64
    image: rb-ocr-backend:latest
    container_name: rb-ocr-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./runs:/app/runs
    environment:
      - TZ=Asia/Almaty
      - DB_HOST=10.0.94.227
      - DB_PORT=5432
      - DB_NAME=rbocrdb
      - DB_USER=rbocruser
      - DB_PASSWORD=rbocruserDEV
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    build: ./ui
    platform: linux/amd64
    image: rb-ocr-ui:latest
    container_name: rb-ocr-ui
    restart: always
    ports:
      - "8501:8501"
    environment:
      - TZ=Asia/Almaty
      - FASTAPI_SERVICE_URL=http://rb-ocr-dev-app-uv01.fortebank.com/rb-ocr/api
    depends_on:
      backend:
        condition: service_healthy
