services:
  db:
    image: postgres:latest
    container_name: postgres_exchange_control
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_exchange_control:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis_exchange_control
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_exchange_control:/data
    command: sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""
    healthcheck:
      test: [ "CMD", "sh", "-c", "redis-cli -a \"$REDIS_PASSWORD\" ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # minio:
  #   image: quay.io/minio/minio
  #   container_name: minio_exchange_control
  #   ports:
  #     - "127.0.0.1:9000:9000"
  #     - "127.0.0.1:9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
  #     MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
  #   volumes:
  #     - minio_exchange_control:/data
  #   command: server --console-address ":9001" /data
  #   healthcheck:
  #     test: [ "CMD", "mc", "ready", "local" ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  backend:
    image: exchange-control
    container_name: app_exchange_control
    command: uvicorn src.main:src --host 0.0.0.0 --port 8000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SECURE: ${MINIO_SECURE}
      MINIO_BUCKET: ${MINIO_BUCKET}
      VERIFY_SSL: ${VERIFY_SSL}
      FRONTEND_CALLBACK_URL: ${FRONTEND_CALLBACK_URL}
      DMZ_URL: ${DMZ_URL}
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - redis
      - db
      # - minio

  worker:
    image: exchange-control
    container_name: worker_exchange_control
    command: celery -A src.core.celery_app.celery_app worker --loglevel=info -Q contracts
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SECURE: ${MINIO_SECURE}
      MINIO_BUCKET: ${MINIO_BUCKET}
      VERIFY_SSL: ${VERIFY_SSL}
      FRONTEND_CALLBACK_URL: ${FRONTEND_CALLBACK_URL}
      DMZ_URL: ${DMZ_URL}
    depends_on:
      - redis
      - db
      # - minio

volumes:
  redis_exchange_control:
  postgres_exchange_control:
  # minio_exchange_control:
